### ISSUE TITLE
KeyError: 'icon-comment'

### ISSUE THREAD

**Issue by knatz-dev** [kivy-garden/garden.iconfonts#5]
Hi 
I really like the idea of using iconfonts with kivy but can't seem to get it to work.

**kv string**

> #: import icon kivy.garden.iconfonts.icon
     ToolBar:
           Button:
                text: "%s"%(icon('icon-comment'))

**Error Message**
`Traceback (most recent call last):
   File "C:\Program Files\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 249, in create_handler
     return eval(value, idmap), bound_list
   File "<string>", line 31, in <module>
   File "C:\Users\User\.kivy\garden\garden.iconfonts\iconfonts.py", line 33, in icon
     s = "[font=%s]%s[/font]" % (font_data[0], unichr(font_data[2][code]))
 KeyError: 'icon-comment'`
 `Traceback (most recent call last):
   File "C:\Program Files\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 597, in _apply_rule
     rctx['ids'])
   File "C:\Program Files\Anaconda3\lib\site-packages\kivy\lang\builder.py", line 254, in create_handler
     cause=tb)
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 31:`
 >>   31:        text: "%s"%(icon('icon-comment'))`

**Comment by knatz-dev** [comment]
replaced 'icon-comment' with 'fa-bold' and it worked so i think this is something that requires a more friendly error message.
