### ISSUE TITLE
Failing with KeyError

### ISSUE THREAD

**Issue by SatyakiDe2019** [kivy-garden/garden.iconfonts#8]
Hi Team,

I'm getting the error while registering the iconfonts -

`from garden.iconfonts import register`

And, the error -

`Traceback (most recent call last):
   File "main.py", line 14, in <module>
     from kivy.garden.iconfonts import register
   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
   File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
   File "<frozen importlib._bootstrap>", line 640, in _load_backward_compatible
 KeyError: 'kivy.garden.iconfonts'
`

I've to reinstall both the kivy garden & then I followed some of the old successful methods available over the internet. Nothing is working it seems.

Any idea?

**Comment by SatyakiDe2019** [comment]
I think I got the solution. 

I did download the zip & unzip that under my project folder & then refer the package this way -

`from garden.iconfonts import register`

And, inside the .kv file -

`#: import icon garden.iconfonts.icon`

It should work for you.
